/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

import javax.swing.JOptionPane;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class ramalan extends javax.swing.JFrame {

    /**
     * Creates new form ramalan
     */

    /**class handler*/
    private class ItemHandler implements ItemListener{    
        @Override
        public void itemStateChanged(ItemEvent event){
            if(comboBulan.getSelectedItem().equals("2")){
                comboHari.removeItem("30");
                comboHari.removeItem("31");
            }
            else{
                comboHari.removeAllItems();
                for(int i=0; i<32; i++){
                    String a = Integer.toString(i);
                    comboHari.addItem(a);
                }
            }
        }
    }   

    /** method zodiac*/
    private static String zodiac(int hari2, int bulan2){
        String astro = "";
        if (bulan2 == 12){ 
            if (hari2 < 22) 
            astro = "Sagittarius"; 
            else
            astro ="Capricorn"; 
        }      
        else if (bulan2 == 1){ 
            if (hari2 < 20) 
            astro = "Capricorn"; 
            else
            astro = "Aquarius"; 
        }     
        else if (bulan2 == 2){ 
            if (hari2 < 19) 
            astro = "Aquarius"; 
            else
            astro = "Pisces"; 
        }     
        else if(bulan2 == 3){ 
            if (hari2 < 21)  
            astro = "Pisces"; 
            else
            astro = "Aries"; 
        } 
        else if (bulan2 == 4){ 
            if (hari2 < 20) 
            astro = "Aries"; 
            else
            astro = "Taurus"; 
        }     
        else if (bulan2 == 5){ 
            if (hari2 < 21) 
            astro = "Taurus"; 
            else
            astro = "Gemini"; 
        }     
        else if(bulan2 == 6){ 
            if (hari2 < 21) 
            astro = "Gemini"; 
            else
            astro = "Cancer"; 
        }      
        else if (bulan2 == 7){ 
            if (hari2 < 23) 
            astro = "Cancer"; 
            else
            astro = "Leo"; 
        }     
        else if(bulan2 == 8){ 
            if (hari2 < 23)  
            astro = "Leo"; 
            else
            astro = "Virgo"; 
        }     
        else if (bulan2 == 9){ 
            if (hari2 < 23) 
            astro = "Virgo"; 
            else
            astro = "Libra"; 
        }     
        else if (bulan2 == 10){ 
            if (hari2 < 23) 
            astro = "Libra"; 
            else
            astro = "Scorpio"; 
        }     
        else if (bulan2 == 11){ 
            if (hari2 < 22) 
            astro = "Scorpio"; 
            else
            astro = "Sagittarius"; 
        }
        return astro;
    }
    
    private ItemHandler handler = new ItemHandler();
    
    public ramalan() {
        initComponents();
        jTextArea1.setEditable(false);
        comboBulan.addItemListener(handler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        comboHari = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbHasil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));
        setForeground(new java.awt.Color(204, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nama :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bulan lahir :");

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboBulan.setToolTipText("");

        comboHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ramalan hari ini :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal lahir :");

        lbHasil.setBackground(new java.awt.Color(0, 255, 153));
        lbHasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHasil.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                                .addComponent(jLabel5)))))
                                .addGap(18, 18, 18)
                                .addComponent(comboHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jButton1)))
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nama2 = nama.getText();
        nama.setText(nama2);
        
        int bulan1 = Integer.parseInt(comboBulan.getSelectedItem().toString());
        int hari1 = Integer.parseInt(comboHari.getSelectedItem().toString());
        
        int index = (int)(Math.random()*4);
        int index1 = (int)(Math.random()*4);
        int index2 = (int)(Math.random()*4);
        String [][] luck = {{"Keuangan : terbaik", "Keuangan : Baik", "Keuangan : kurang baik", "Keuangan : Buruk"},
            {"Kesehatan : Terbaik", "Kesehatan : Baik", "Kesehatan : kurang baik", "Kesehatan : buruk"},
            {"Jodoh : Terbaik", "Jodoh : Baik", "Jodoh : kurang baik", "Jodoh : buruk"}};
        
        if(nama2.equals("") || bulan1 == 0 || hari1 == 0){ 
            JOptionPane.showMessageDialog(this, "Silahkan isi tanggal lahir dan nama");
        }
        else{
            String jadi = zodiac(hari1, bulan1);
            
            lbHasil.setText(nama2 + ", zodiak anda " + jadi);
            jTextArea1.setText(luck[0][index] +'\n'+ luck[1][index1] +'\n'+ luck[2][index2]
            +'\n'+ "\nSemoga hari anda menyenangkan.");
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nama.setText("");
        comboBulan.setSelectedItem("0");
        comboHari.setSelectedItem("0");
        lbHasil.setText("");
        jTextArea1.setText("");
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ramalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ramalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ramalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ramalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ramalan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<String> comboHari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbHasil;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables
}
